Update UI text to match to actual behavior
FlexConfirmMail/Thunderbird pull request #45
Opened 2024-05-28 08:14 UTC by piroor

# Which issue(s) this PR fixes:

N/A

# What this PR does / why we need it:

This updates  UI labels matching to changes introduced by the PR #43

# How to verify the fixed issue:

Install XPI from the branch and see UI labels.

## The steps to verify:

1. Install XPI.
2. Go to the options page of FlexConfirmMail.

## Expected result:

Natural descriptions around internals.

2024-05-28 08:54 UTC, HashidaTKS requested changes

2024-05-28 08:54 UTC, HashidaTKS commented on webextensions/_locales/ja/messages.json
>    "config_skipConfirmationForInternalMail_label": { "message": "すべての宛先が登録済みドメインのメール送信時は確認ダイアログを表示しない" },
```suggestion
  "config_skipConfirmationForInternalMail_label": { "message": "すべての宛先が登録済みパターンのメール送信時は確認ダイアログを表示しない" },
```

2024-05-28 08:54 UTC, HashidaTKS commented on webextensions/_locales/ja/messages.json
>    "config_skipConfirmationForInternalMail_label": { "message": "すべての宛先が登録済みドメインのメール送信時は確認ダイアログを表示しない" },
ここはパターンが適切なように思いました。
他に「ドメイン」を使っている箇所は「ドメイン」のままが適切なように見えます。

2024-05-29 01:33 UTC, piroor commented on webextensions/_locales/ja/messages.json
>    "config_skipConfirmationForInternalMail_label": { "message": "すべての宛先が登録済みドメインのメール送信時は確認ダイアログを表示しない" },
ご指摘ありがとうございます、見落としていました。ただ、ここは英語のロケールでは Skip confirmation if all recipients are internals としていたところだったので、表現を英語に合わせて、ドメインともパターンとも言わなくてもよいように改めてみました。

2024-05-29 01:39 UTC, HashidaTKS commented
LGTM

2024-05-29 01:40 UTC, HashidaTKS approved these changes

2024-05-29 01:41 UTC, merged